#
# $Id: Makefile.xpvm,v 4.50 1998/04/09 21:11:23 kohl Exp $
#

install:
	cd src ; $(PVM_ROOT)/lib/aimk install

winstall:
	cd src ; $(PVM_ROOT)/lib/aimk winstall

arch_install:
	cd src ; $(PVM_ROOT)/lib/aimk tcls

again:
	cd src ; $(PVM_ROOT)/lib/aimk again

clean:
	cd src ; $(PVM_ROOT)/lib/aimk clean
	cd tracer ; $(PVM_ROOT)/lib/aimk clean

veryclean:
	cd src ; $(PVM_ROOT)/lib/aimk veryclean
	cd tracer ; $(PVM_ROOT)/lib/aimk veryclean

